### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by jisungbin** [junyoungleee/Done#1]
안녕하세요! 같은 CMC 9기에 안드로이드 개발자로 참여한 성빈 입니다. 

결국엔 팔레트 팀으로 오진 않았지만, 팔레트 팀도 우선순위 였던 팀이라 관심이 많이 있어서 이 레포에 watch를 걸어두었습니다.
코드를 보다가 개선이 필요한 부분들이 꽤 많이 보여서 이 부분에 있어서 조언을 드려도 괜찮을까요?

팀 프로젝트인데, 외부 팀인 제가 바로 개입하는건 맞지 않는거 같아 여쭤봅니다.

@junyoungleee

**Comment by junyoungleee** [comment]
@jisungbin 
안녕하세요! 제가 issue를 지금 확인했네요ㅠㅠ 
아직 많이 부족한 상태라 조언 환영합니다!

**Comment by jisungbin** [comment]
긍정적인 답변 감사합니다!
